--- 
project_url: https://github.com/dharmafly/noodle
ga_id: UA-34978047-5
permalink: /:title
theme: ocean
safe: false
lsi: false
future: true
download_links: 
- href: https://github.com/dharmafly/noodle/zipball/master
  title: The repo's latest codebase (zip). Potentially unstable.
  subtext: (master)
  text: Edge
markdown: maruku
exclude: 
- README.md
- assets
- FiddlerRules.farx
sections: 
- name: Overview
  path: /index.html
- name: Reference
  path: /reference/index.html
server: false
pygments: false
version: 0.0.3
twitter_url: https://twitter.com/dharmafly
lang: javascript
project_name: noodle
quote: 
- quote: Ink is better than the best memory.
- cite: Chinese proverb
auto: false
scripts: 
- src: //ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js
baseurl: /
