--- 
version: 0.0.1
sections: 
- path: /index.html
  name: Overview
- path: /reference/index.html
  name: Reference
lsi: false
lang: javascript
baseurl: /
auto: false
project_url: https://github.com/dharmafly/noodle
theme: ocean
quote: 
- quote: 
- cite: 
ga_id: UA-34978047-6
server: false
twitter_url: https://twitter.com/dharmafly
scripts: 
- src: 
download_links: 
- href: https://github.com/dharmafly/noodle/zipball/master
  title: The repo's latest codebase (zip). Potentially unstable.
  text: Edge
  subtext: (master)
project_name: Noodle
permalink: /:title
exclude: 
- README.md
- assets
- FiddlerRules.farx
safe: false
future: true
pygments: false
markdown: maruku
