--- 
project_name: noodle
project_url: https://github.com/dharmafly/noodle
version: 0.1.0
jquery_no_conflict: true
theme: ocean
twitter_url: https://twitter.com/dharmafly
twitter_name: Dharmafly
lang: javascript
scripts: 
- src: //ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js
quote: 
ga_id: UA-34978047-5
download_links: 
- text: Edge
  subtext: (master)
  href: https://github.com/dharmafly/noodle/zipball/master
  title: The repo's latest codebase (zip). Potentially unstable.
sections: 
- path: /index.html
  name: Overview
- path: /reference/index.html
  name: Reference
safe: false
auto: false
server: false
future: true
lsi: false
pygments: false
markdown: maruku
permalink: /:title
baseurl: /
exclude: 
- README.md
- assets
- FiddlerRules.farx
