--- 
twitter_url: https://twitter.com/dharmafly
ga_id: UA-34978047-6
sections: 
- path: /index.html
  name: Overview
- path: /reference/index.html
  name: Reference
safe: false
theme: ocean
scripts: 
- src: 
server: false
lsi: false
pygments: false
permalink: /:title
project_name: Noodle
markdown: maruku
exclude: 
- README.md
- assets
- FiddlerRules.farx
future: true
baseurl: /
download_links: 
- title: The repo's latest codebase (zip). Potentially unstable.
  text: Edge
  href: https://github.com/dharmafly/noodle/zipball/master
  subtext: (master)
lang: javascript
quote: 
- quote: 
- cite: 
auto: false
project_url: https://github.com/dharmafly/noodle
version: 0.0.1
