--- 
markdown: maruku
auto: false
server: false
baseurl: /
lang: javascript
pygments: false
theme: ocean
safe: false
project_name: Noodle
ga_id: UA-34978047-6
project_url: https://github.com/dharmafly/noodle
lsi: false
scripts: 
- src: 
download_links: 
- href: https://github.com/dharmafly/noodle/zipball/master
  subtext: (master)
  text: Edge
  title: The repo's latest codebase (zip). Potentially unstable.
sections: 
- path: /index.html
  name: Overview
- path: /reference/index.html
  name: Reference
future: true
permalink: /:title
exclude: 
- README.md
- assets
- FiddlerRules.farx
version: 0.0.1
quote: 
- quote: 
- cite: 
twitter_url: https://twitter.com/dharmafly
