safe:        false
auto:        false
server:      false
baseurl:     /

future:      true
lsi:         false
pygments:    false
markdown:    maruku
permalink:   title

exclude: ['README.md']


PROJECT_NAME: Project Name
GITHUB_CURRENT_VERSION: 1.0
GITHUB_PROJECT_URL: https://github.com/dharmafly/dharmafly-docs