--- 
theme: ocean
safe: false
future: true
markdown: maruku
sections: 
- name: Overview
  path: /index.html
- name: Reference
  path: /reference/index.html
lsi: false
baseurl: /
project_name: Noodle
version: 0.0.1
pygments: false
lang: javascript
ga_id: UA-34978047-6
exclude: 
- README.md
- assets
- FiddlerRules.farx
twitter_url: https://twitter.com/dharmafly
quote: 
- quote: 
- cite: 
permalink: /:title
project_url: https://github.com/dharmafly/noodle
scripts: 
- src: 
download_links: 
- text: Edge
  href: https://github.com/dharmafly/noodle/zipball/master
  subtext: (master)
  title: The repo's latest codebase (zip). Potentially unstable.
server: false
auto: false
