--- 
download_links: 
- title: The repo's latest codebase (zip). Potentially unstable.
  href: https://github.com/dharmafly/noodle/zipball/master
  text: Edge
  subtext: (master)
quote: 
- quote: 
- cite: 
future: true
project_name: Noodle
baseurl: /
auto: false
sections: 
- name: Overview
  path: /index.html
- name: Reference
  path: /reference/index.html
ga_id: UA-34978047-6
markdown: maruku
exclude: 
- README.md
- assets
- FiddlerRules.farx
version: 0.0.1
lang: javascript
project_url: https://github.com/dharmafly/noodle
scripts: 
- src: 
safe: false
server: false
permalink: /:title
theme: ocean
twitter_url: https://twitter.com/dharmafly
lsi: false
pygments: false
