# Your project's details
PROJECT_NAME: Project Name
GITHUB_CURRENT_VERSION: 1.0
GITHUB_PROJECT_URL: https://github.com/dharmafly/dharmafly-docs

# Optional extras
GITHUB_ZIP_URL: https://github.com/dharmafly/dharmafly-docs/zipball/gh-pages
TWITTER_PROJECT_URL: https://twitter.com/dharmafly
# javascript, css or html5
LANG: javascript


# Page names (paths are currently hard-coded to match directory names / site categories)
sections:
 - path: 
   name: Overview 
 - path: reference
   name: Reference 
  
# Add your project's scripts here to be available to any examples
PROJECT_SCRIPTS:
- src: https://raw.github.com/dharmafly/jquery.promises/master/image.js
- src: https://raw.github.com/dharmafly/jquery.promises/master/timer.js

# A quote to add at the footer of your project page
PROJECT_QUOTE:
  quote:  Promises are the uniquely human way of ordering the future, making it predictable and reliable to the extent that this is humanly possible.
  cite: Hannah Arendt

font: Forum
  
###############################


# Jekyll options

safe:        false
auto:        false
server:      false

future:      true
lsi:         false
pygments:    false
markdown:    maruku
permalink:   /:title
baseurl:     /

exclude: ['README.md', 'assets', 'FiddlerRules.farx']
