---
project_name: Noodle
project_url: https://github.com/dharmafly/noodle
version: 0.0.1
theme: ocean
twitter_url: https://twitter.com/dharmafly
lang: javascript
scripts:
- src: http://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js
quote:
- quote: 
- cite: 
ga_id: UA-34978047-6
download_links:
- text: Edge
  subtext: (master)
  href: https://github.com/dharmafly/noodle/zipball/master
  title: The repo's latest codebase (zip). Potentially unstable.
sections:
- path: /index.html
  name: Overview
- path: /reference/index.html
  name: Reference
safe: false
auto: false
server: false
future: true
lsi: false
pygments: false
markdown: maruku
permalink: /:title
baseurl: /
exclude:
- README.md
- assets
- FiddlerRules.farx
