# Your project's details
PROJECT_NAME: Project Name
GITHUB_CURRENT_VERSION: 1.0
GITHUB_PROJECT_URL: https://github.com/dharmafly/dharmafly-docs


# Location of Reference/API page
REFERENCE: 
  name: Reference
  
# Add your project's scripts here to be available to any examples
PROJECT_SCRIPTS:
- location: https://raw.github.com/dharmafly/jquery.promises/master/image.js
- location: https://raw.github.com/dharmafly/jquery.promises/master/timer.js

###############################



# Jekyll options

safe:        false
auto:        false
server:      false

future:      true
lsi:         false
pygments:    false
markdown:    maruku
permalink:   /:title
baseurl:     /

exclude: ['README.md']
