# The project
PROJECT_NAME: Dharmafly Docs
# Version number as a string
VERSION: '1.0'
GITHUB_PROJECT_URL: https://github.com/dharmafly/dharmafly-docs

# Site theme (options: forest, ocean, horus, seagrass, sundae, slate)
THEME: sundae


############ Options

# URLs
DOWNLOAD_LINKS:
  - text: Master branch
    href: https://github.com/dharmafly/dharmafly-docs/downloads
    title: Main working version of the code
  - text: Dharmafly Docs
    subtext: v{{ version }}.min
    href: '#'
  - text: Satya build tool
    href: https://github.com/dharmafly/dharmafly-docs/tree/command-line-tool
    title: command line tool to build a project version of Dharmafly Docs
  - text: Github pages branch
    subtext: (current)
    href: https://github.com/dharmafly/dharmafly-docs/tree/gh-pages
    title: The working branch
TWITTER_PROJECT_URL: https://twitter.com/dharmafly

# Primary language or technology (options: javascript, css, html5)
LANG: html5

# Documentation site scripts
SCRIPTS:
- src: //ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js
- src: https://raw.github.com/dharmafly/jquery.promises/master/image.js
- src: https://raw.github.com/dharmafly/jquery.promises/master/timer.js

# Footer quote
QUOTE:
  quote: Ink is better than the best memory.
  cite: Chinese proverb

# Site analytics
GA_ID:

# Page names
# The following paths are hard-coded to match directory names / site categories.
sections:
 - path: /index.html
   name: Overview
 - path: /reference/index.html
   name: Reference

############ Deprecated 

# Link from overview to reference
REFERENCE_LINK_TEXT: "Complete documentation can be found here:"

GITHUB_ZIP_URL: https://github.com/dharmafly/dharmafly-docs/zipball/gh-pages

############ Jekyll options

safe:        false
auto:        false
server:      false

future:      true
lsi:         false
pygments:    false
markdown:    maruku
permalink:   /:title
baseurl:     /

exclude: ['README.md', 'assets', 'FiddlerRules.farx']
